[package]
name = "ghl"
version = "0.1.0"
authors = ["Rrogntudju"]
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
soup = "0.5"
url = "2"
regex = "1"
rulex = "0.2"


